adding prefix to all resources as capx-
nutanix-cloud-native/cluster-api-provider-nutanix pull request #13
Opened 2022-04-10 19:03 UTC by deepakm-ntnx

This will make prefix of all resource names to capx-

TODO: testing pending

2022-04-11 19:15 UTC, tuxtof requested changes
ok on the idea but we need to clean some name to avoid redundant name like

capx-nutanix-creds

2022-04-20 05:21 UTC, tuxtof commented
@deepakm-ntnx can you clean the creds name please

2022-05-30 09:40 UTC, tuxtof commented
@deepakm-ntnx any update on this one ?

2022-06-07 12:38 UTC, tuxtof requested changes

2022-06-07 16:56 UTC, deepakm-ntnx commented on tilt-provider.json
> +{
its suggested by cluster-api itself https://cluster-api.sigs.k8s.io/developer/tilt.html#developing-cluster-api-with-tilt

for a simplified workflow that offers easy deployments and rapid iterative builds.

2022-06-07 17:07 UTC, deepakm-ntnx commented on tilt-provider.json
> +{
also, many other providers also ahve this file including cluster-api repo itself and vsphere etc

2022-06-07 17:08 UTC, deepakm-ntnx commented on docs/getting_started.md
> +  - CLUSTER_NAME                     (defaults to mycluster)
this is the exact output from list-variables. why do you think its not supported? are you saying clusterctl mandates cluster name on cli even if its set?

2022-06-07 17:22 UTC, deepakm-ntnx commented on config/manager/manager.yaml
> +      # securityContext:
Agree with you but for following reason, have temporarily commented it out
1. we already use nonroot image as follows
<pre>
2022/05/27 15:02:00 Using base gcr.io/distroless/static:nonroot@sha256:2556293984c5738fc75208cce52cf0a4762c709cf38e4bf8def65a61992da0ad for github.com/nutanix-cloud-native/cluster-api-provider-nutanix
</pre>
2. when i was running tilt, i was getting following error 
<pre>
  Normal   Scheduled  35s               default-scheduler  Successfully assigned capx-system/capx-controller-manager-6586d6f577-tqbzf to tilt-test-cluster-control-plane
  Normal   Pulling    33s               kubelet            Pulling image "gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0"
  Normal   Pulled     21s               kubelet            Successfully pulled image "gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0" in 11.737437542s
  Normal   Created    21s               kubelet            Created container kube-rbac-proxy
  Normal   Started    21s               kubelet            Started container kube-rbac-proxy
  Normal   Pulled     6s (x4 over 21s)  kubelet            Container image "ghcr.io/nutanix-cloud-native/cluster-api-provider-nutanix/controller/ghcr.io_nutanix-cloud-native_cluster-api-provider-nutanix_controller:tilt-5cf0bb2c082e5dcd" already present on machine
  Warning  Failed     6s (x4 over 21s)  kubelet            Error: container has runAsNonRoot and image will run as root (pod: "capx-controller-manager-6586d6f577-tqbzf_capx-system(913940f1-720d-49b7-ad82-c3e6959be4f4)", container: manager) <====
</pre>

will explore more if we can set some setting in tilt. i didnt find this set in other providers as well as a data point.

2022-06-08 06:55 UTC, tuxtof commented on docs/getting_started.md
> +  - CLUSTER_NAME                     (defaults to mycluster)
yes never use CLUSTER_NAME ENV variable , you always need to specify it on command line

2022-06-08 17:06 UTC, tuxtof approved these changes

2022-06-08 17:08 UTC, yannickstruyf3 approved these changes

2022-06-08 17:17 UTC, merged

2022-06-08 17:30 UTC, deepakm-ntnx commented on config/manager/manager.yaml
> +      # securityContext:
we are using nonRoot user inside container so technically we are. will file a tracker to make tilt work with this setting as well